# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yujin Chang
description: Yujin Chang description
baseurl: ""
url: "https://yujin-chang.github.io"
og_image: ./assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research #Work
    - name: Resume #Blog

footer:
  show_powered_by: false
  contact:
    - type: email
      name: Gmail
      value: yujinchang804@gmail.com
    - type: email
      name: Purdue
      value: yjchang@gmail.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/yjchangcrypt
    - type: github
      name: GitHub
      link: http://github.com/YourGitHubUsername
#    - type: dribbble
#      name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - type: rss
#      name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
